<a href="https://colab.research.google.com/github/NathanMcCormack/Principles_of_ML_Assignment1/blob/main/ML_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files

In [3]:
uploaded = files.upload()
df = pd.read_csv("Data.csv")
df.head()

Saving Data.csv to Data.csv

   Participant      HR      respr   Time(sec)  Label
0            2  118.00  12.127693  1644227583      0
1            2  113.50  12.127693  1644227584      0
2            2   93.00  12.127693  1644227585      0
3            2   93.25  12.127693  1644227586      0
4            2   86.40  12.127693  1644227587      0

#Dataset Quality & Structure
Here i will look for any inconsistencies in the dataset that would disrupt our training. So noise, missing values, duplicate timestamps for each participant. etc

In [9]:
#shows how many rows and columns
print(df.shape)

#information about each column (data types)
df.info()

#the number of participants in the dataset - 34
df["Participant"].nunique()

(112516, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112516 entries, 0 to 112515
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Participant  112516 non-null  int64
 1   HR           112472 non-null  float64
 2   respr        112516 non-null  float64
 3   Time(sec)    112516 non-null  int64
 4   Label        112516 non-null  int64
dtypes: float64(2), int64(3)
memory usage: 4.3 MB

34

##getting missing values & duplicates

In [10]:
#shows us the total number of missing values for each column
df.isnull().sum()

Participant     0
HR             44
respr           0
Time(sec)       0
Label           0
dtype: int64

In [18]:
missing_hr = df["HR"].isnull().sum()
total_rows = len(df)

missing_percentage = missing_hr/total_rows * 100

print(missing_percentage)
#this shows us that %0.04 of HR values are missing. Since we have about 112k values we can remove these missing data points rather than trying ot replace them as it wont -
#have a major impact on our training but before we remove them we need to analyse where they are located. if all 44 missing data points are in consecutive rows; removing
#them would have an impact on our training

0.03910554943296954

In [24]:
#looking for duplicate values - we would ignore any duplicate HR and respiration values as we are very likely to see duplicates in those fields, what we want to look for is if
#there are any duplicate ID && timestamp, to see if multiple values were entered for one timestamp

#using the pandas "subset" we can ignore other columns when looking for duplicates
df.duplicated(subset=["Participant", "Time(sec)"]).sum()

np.int64(0)

##Assessing anomolies in the data

In [37]:
#looking at the max, min values in HR and respiration, lookign for outliers
#immedietley I notice that the min value for respirations is 5. for a regular resting period that is quite low. The only way I could see this being realistic is if
#participants were guided through a breathing exercise during the experiment. i will need to check this
print(df.describe())

#there seems to be a lot of respiration values below 7 (over 400 rows across multiple participants) so my assumption was wrong and this does not seem to be an anomoly
df[df["respr"] < 7]

         Participant             HR          respr     Time(sec)  \
count  112516.000000  112472.000000  112516.000000  1.125160e+05
mean       18.475470      80.216177      12.465482  1.645692e+09
std         9.871133      12.732206       2.030810  8.179419e+05
min         2.000000      49.000000       5.204728  1.644228e+09
25%        10.000000      71.330000      11.191843  1.644846e+09
50%        18.000000      77.890000      12.743635  1.645461e+09
75%        27.000000      87.020000      13.877519  1.646648e+09
max        35.000000     146.780000      18.163532  1.646842e+09

               Label
count  112516.000000
mean        0.327198
std         0.469192
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000

       Participant      HR     respr   Time(sec)  Label
52644           17   79.60  6.995449  1645458937      0
52645           17   80.28  6.931449  1645458938      0
52646           17   80.65  6.931449  1645458939      0
52647           17   81.00  6.931449  1645458940      0
52648           17   81.35  6.931449  1645458941      0
...            ...     ...       ...         ...    ...
89615           29  103.38  6.813774  1646657293      0
89616           29  102.90  6.877774  1646657294      0
89617           29  102.45  6.941774  1646657295      0
89618           29  101.95  6.992974  1646657296      0
89619           29  101.42  6.992974  1646657297      0

[421 rows x 5 columns]

In [ ]:
#checking which participants recorded the low respiration